/**
 * High-frequency irregular bases — hand list beats broken heuristics.
 * Prefixed verbs inherit via {@link resolveIrregular} when the base is prefixable.
 */
export const IRREGULAR: Record<string, string[]> = {
  byť: [
    "som",
    "si",
    "je",
    "sme",
    "ste",
    "sú",
    "bol",
    "bola",
    "bolo",
    "boli",
    "budem",
    "budeš",
    "bude",
    "budeme",
    "budete",
    "budú",
  ],
  mať: ["mám", "máš", "má", "máme", "máte", "majú", "mal", "mala", "malo", "mali"],
  ísť: [
    "idem",
    "ideš",
    "ide",
    "ideme",
    "idete",
    "idú",
    "išiel",
    "išla",
    "išlo",
    "išli",
    "pôjdem",
    "pôjdeš",
    "pôjde",
  ],
  // ísť derivatives keep their own stems — do not prefix from ísť.
  prísť: [
    "prídem",
    "prídeš",
    "príde",
    "prídeme",
    "prídete",
    "prídu",
    "prišiel",
    "prišla",
  ],
  odísť: ["odídem", "odídeš", "odíde", "odišiel", "odišla"],
  nájsť: ["nájdem", "nájdeš", "nájde", "našiel", "našla"],
  dôjsť: ["dôjdem", "dôjdeš", "dôjde", "došiel", "došla"],
  vyjsť: ["vyjdem", "vyjdeš", "vyjde", "vyšiel", "vyšla"],
  zájsť: ["zájdem", "zájdeš", "zájde", "zašiel", "zašla"],
  vojsť: ["vojdem", "vojdeš", "vojde", "vošiel", "vošla"],
  ujsť: ["ujdem", "ujdeš", "ujde", "ušiel", "ušla"],
  zísť: ["zídem", "zídeš", "zíde", "zišiel", "zišla"],
  obísť: ["obídem", "obídeš", "obíde", "obišiel", "obišla"],
  prejsť: ["prejdem", "prejdeš", "prejde", "prešiel", "prešla"],
  podísť: ["podídem", "podídeš", "podíde", "podišiel", "podišla"],
  rozísť: ["rozídem", "rozídeš", "rozíde", "rozišiel", "rozišla"],
  vzísť: ["vzídem", "vzídeš", "vzíde", "vzišiel", "vzišla"],
  neísť: ["neidem", "neideš", "neide", "neideme", "neidete", "neidú"],
  chodiť: ["chodím", "chodíš", "chodí", "chodíme", "chodíte", "chodia", "chodil"],
  jesť: ["jem", "ješ", "je", "jeme", "jete", "jedia", "jedol", "jedla", "jedlo", "jedli"],
  vedieť: [
    "viem",
    "vieš",
    "vie",
    "vieme",
    "viete",
    "vedia",
    "vedel",
    "vedela",
    "vedelo",
    "vedeli",
  ],
  vidieť: [
    "vidím",
    "vidíš",
    "vidí",
    "vidíme",
    "vidíte",
    "vidia",
    "videl",
    "videla",
    "videlo",
    "videli",
  ],
  môcť: [
    "môžem",
    "môžeš",
    "môže",
    "môžeme",
    "môžete",
    "môžu",
    "mohol",
    "mohla",
    "mohlo",
    "mohli",
  ],
  musieť: [
    "musím",
    "musíš",
    "musí",
    "musíme",
    "musíte",
    "musia",
    "musel",
    "musela",
    "muselo",
    "museli",
  ],
  chcieť: [
    "chcem",
    "chceš",
    "chce",
    "chceme",
    "chcete",
    "chcú",
    "chcel",
    "chcela",
    "chcelo",
    "chceli",
  ],
  vziať: ["vezmem", "vezmeš", "vezme", "vezmeme", "vezmete", "vezmú", "vzal", "vzala"],
  dať: ["dám", "dáš", "dá", "dáme", "dáte", "dajú", "dal", "dala", "dalo", "dali"],
  povedať: ["poviem", "povieš", "povie", "povieme", "poviete", "povedia", "povedal"],
  brať: [
    "beriem",
    "berieš",
    "berie",
    "berieme",
    "beriete",
    "berú",
    "ber",
    "berte",
    "bral",
    "brala",
    "bralo",
    "brali",
  ],
  prať: [
    "periem",
    "perieš",
    "perie",
    "perieme",
    "periete",
    "perú",
    "per",
    "perte",
    "pral",
  ],
  písať: [
    "píšem",
    "píšeš",
    "píše",
    "píšeme",
    "píšete",
    "píšu",
    "píš",
    "píšte",
    "písal",
    "písala",
  ],
  kázať: ["kážem", "kážeš", "káže", "kážeme", "kážete", "kážu", "káž", "kážte", "kázal"],
  plakať: [
    "plačem",
    "plačeš",
    "plače",
    "plačeme",
    "plačete",
    "plačú",
    "plač",
    "plačte",
    "plakal",
  ],
  skákať: [
    "skáčem",
    "skáčeš",
    "skáče",
    "skáčeme",
    "skáčete",
    "skáču",
    "skáč",
    "skáčte",
    "skákal",
  ],
  hádzať: [
    "hádžem",
    "hádžeš",
    "hádže",
    "hádžeme",
    "hádžete",
    "hádžu",
    "hádž",
    "hádžte",
    "hádzal",
  ],
  lámať: ["lámem", "lámeš", "láme", "lámeme", "lámete", "lámu", "lámal"],
  orať: ["orem", "oreš", "ore", "oreme", "orete", "orú", "oral"],
  klamať: ["klamem", "klameš", "klame", "klameme", "klamete", "klamú", "klamal"],
  viazať: ["viažem", "viažeš", "viaže", "viažeme", "viažete", "viažu", "viazal"],
  kopať: ["kopem", "kopeš", "kope", "kopeme", "kopete", "kopú", "kopal"],
  spať: [
    "spím",
    "spíš",
    "spí",
    "spíme",
    "spíte",
    "spia",
    "spi",
    "spite",
    "spal",
    "spala",
  ],
  stáť: [
    "stojím",
    "stojíš",
    "stojí",
    "stojíme",
    "stojíte",
    "stoja",
    "stál",
    "stála",
    "stálo",
  ],
  báť: ["bojím", "bojíš", "bojí", "bojíme", "bojíte", "boja", "bál", "bála"],
  // Soft -ať / -ieť → -ím (also covered by heuristics; listed for prefix inheritance).
  bežať: ["bežím", "bežíš", "beží", "bežíme", "bežíte", "bežia", "bežal"],
  ležať: ["ležím", "ležíš", "leží", "ležíme", "ležíte", "ležia", "ležal"],
  držať: ["držím", "držíš", "drží", "držíme", "držíte", "držia", "držal"],
  kričať: ["kričím", "kričíš", "kričí", "kričíme", "kričíte", "kričia", "kričal"],
  mlčať: ["mlčím", "mlčíš", "mlčí", "mlčíme", "mlčíte", "mlčia", "mlčal"],
  trčať: ["trčím", "trčíš", "trčí", "trčíme", "trčíte", "trčia", "trčal"],
  sedieť: ["sedím", "sedíš", "sedí", "sedíme", "sedíte", "sedia", "sedel"],
  horieť: ["horím", "horíš", "horí", "horíme", "horíte", "horia", "horel"],
  bolieť: ["bolím", "bolíš", "bolí", "bolíme", "bolíte", "bolia", "bolel"],
  visieť: ["visím", "visíš", "visí", "visíme", "visíte", "visia", "visel"],
  trpieť: ["trpím", "trpíš", "trpí", "trpíme", "trpíte", "trpia", "trpel"],
  myslieť: ["myslím", "myslíš", "myslí", "myslíme", "myslíte", "myslia", "myslel"],
  hľadieť: ["hľadím", "hľadíš", "hľadí", "hľadíme", "hľadíte", "hľadia", "hľadel"],
  vravieť: ["vravím", "vravíš", "vraví", "vravíme", "vravíte", "vravia", "vravel"],
  // Consonant-stem infinitives.
  niesť: [
    "nesiem",
    "nesieš",
    "nesie",
    "nesieme",
    "nesiete",
    "nesú",
    "nes",
    "neste",
    "niesol",
    "niesla",
  ],
  viesť: [
    "vediem",
    "vedieš",
    "vedie",
    "vedieme",
    "vediete",
    "vedú",
    "veď",
    "veďte",
    "viedol",
    "viedla",
  ],
  viezť: [
    "veziem",
    "vezieš",
    "vezie",
    "vezieme",
    "veziete",
    "vezú",
    "vez",
    "vezte",
    "viezol",
    "viezla",
  ],
  rásť: [
    "rastiem",
    "rastieš",
    "rastie",
    "rastieme",
    "rastiete",
    "rastú",
    "rastol",
    "rastla",
  ],
  piecť: ["pečiem", "pečieš", "pečie", "pečieme", "pečiete", "pečú", "piekol", "piekla"],
  tiecť: ["tečiem", "tečieš", "tečie", "tečieme", "tečiete", "tečú", "tiekol", "tiekla"],
  liezť: ["leziem", "lezieš", "lezie", "lezieme", "leziete", "lezú", "liezol", "liezla"],
  klásť: [
    "kladiem",
    "kladieš",
    "kladie",
    "kladieme",
    "kladiete",
    "kladú",
    "kladol",
    "kladla",
  ],
  pásť: ["pasiem", "pasieš", "pasie", "pasieme", "pasiete", "pasú", "pásol", "pásla"],
  // Short -iť / -yť.
  piť: [
    "pijem",
    "piješ",
    "pije",
    "pijeme",
    "pijete",
    "pijú",
    "pi",
    "pite",
    "pil",
    "pila",
  ],
  biť: [
    "bijem",
    "biješ",
    "bije",
    "bijeme",
    "bijete",
    "bijú",
    "bi",
    "bite",
    "bil",
    "bila",
  ],
  šiť: [
    "šijem",
    "šiješ",
    "šije",
    "šijeme",
    "šijete",
    "šijú",
    "ši",
    "šite",
    "šil",
    "šila",
  ],
  žiť: [
    "žijem",
    "žiješ",
    "žije",
    "žijeme",
    "žijete",
    "žijú",
    "ži",
    "žite",
    "žil",
    "žila",
  ],
  kryť: ["kryjem", "kryješ", "kryje", "kryjeme", "kryjete", "kryjú", "kryl", "kryla"],
  myť: ["myjem", "myješ", "myje", "myjeme", "myjete", "myjú", "myl", "myla"],
  // -nem / -ujem irregulars.
  stať: ["stanem", "staneš", "stane", "staneme", "stanete", "stanú", "stal", "stala"],
  ostať: [
    "ostanem",
    "ostaneš",
    "ostane",
    "ostaneme",
    "ostanete",
    "ostanú",
    "ostal",
    "ostala",
  ],
  začať: ["začnem", "začneš", "začne", "začneme", "začnete", "začnú", "začal", "začala"],
  počuť: [
    "počujem",
    "počuješ",
    "počuje",
    "počujeme",
    "počujete",
    "počujú",
    "počul",
    "počula",
  ],
  priať: ["prajem", "praješ", "praje", "prajeme", "prajete", "prajú", "prial", "priala"],
  smieť: ["smiem", "smieš", "smie", "smieme", "smiete", "smejú", "smel", "smela"],
  umrieť: ["umriem", "umrieš", "umrie", "umrieme", "umriete", "umrú", "umrel", "umrela"],
  zomrieť: [
    "zomriem",
    "zomrieš",
    "zomrie",
    "zomrieme",
    "zomriete",
    "zomrú",
    "zomrel",
    "zomrela",
  ],
  hnať: [
    "ženem",
    "ženieš",
    "ženie",
    "ženieme",
    "ženiete",
    "ženú",
    "žeň",
    "žeňte",
    "hnal",
    "hnala",
  ],
  rozumieť: [
    "rozumiem",
    "rozumieš",
    "rozumie",
    "rozumieme",
    "rozumiete",
    "rozumejú",
    "rozumel",
    "rozumela",
  ],
};
