import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { ROOT } from "../lib/paths";
import { resolveFoucBoots, type FoucBootTarget } from "./registry";

const BUN_PACKAGE_MANAGER = /^bun@(\d+\.\d+\.\d+)/;

/** `package.json` `packageManager`, e.g. `bun@1.2.19` → `1.2.19`. */
export function requiredFoucBunVersion(packageManager: string | undefined): string {
  const version = packageManager?.match(BUN_PACKAGE_MANAGER)?.[1];
  if (!version) {
    throw new Error(
      'package.json "packageManager" must be "bun@x.y.z" so FOUC boots stay reproducible.',
    );
  }
  return version;
}

/**
 * Bun's minifier is not stable across versions. CI pins `packageManager`;
 * generating with anything else changes the committed IIFE hash.
 * Returns null when the running bun matches.
 */
export function foucBunMismatchMessage(actual: string, required: string): string | null {
  if (actual.trim() === required) return null;

  return [
    `FOUC boots must be built with bun ${required} (package.json packageManager).`,
    `This process is bun ${actual.trim()}.`,
    "A different Bun minify changes the committed IIFE and fails scripts/fouc/generate.test.ts on CI.",
    `Install the pinned version: curl -fsSL https://bun.sh/install | bash -s "bun-v${required}"`,
  ].join(" ");
}

function assertFoucBunVersion(): void {
  const pkg = JSON.parse(readFileSync(path.join(ROOT, "package.json"), "utf8")) as {
    packageManager?: string;
  };
  const required = requiredFoucBunVersion(pkg.packageManager);
  const actual = execFileSync("bun", ["--version"], { encoding: "utf8" });
  const message = foucBunMismatchMessage(actual, required);
  if (message) throw new Error(message);
}

export function buildFoucBootIife(entry: string): string {
  assertFoucBunVersion();

  const dir = mkdtempSync(path.join(tmpdir(), "fouc-boot-"));
  const outfile = path.join(dir, "boot.js");

  try {
    execFileSync(
      "bun",
      [
        "build",
        entry,
        "--outfile",
        outfile,
        "--format",
        "iife",
        "--target",
        "browser",
        "--minify",
      ],
      {
        cwd: ROOT,
        stdio: ["ignore", "pipe", "pipe"],
        encoding: "utf8",
      },
    );

    return readFileSync(outfile, "utf8").trim();
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

export function renderFoucBootModule(exportName: string, iife: string): string {
  return [
    "/** Generated by `bun run fouc:boot` — do not edit. */",
    `export const ${exportName} = ${JSON.stringify(iife)};`,
    "",
  ].join("\n");
}

export function hashFoucBootScript(source: string): string {
  return createHash("sha256").update(source.replace(/\r\n/g, "\n")).digest("hex");
}

export function writeFoucBoot(target: FoucBootTarget): {
  iife: string;
  moduleSource: string;
} {
  const iife = buildFoucBootIife(target.entry);
  const moduleSource = renderFoucBootModule(target.exportName, iife);
  writeFileSync(target.out, moduleSource, "utf8");
  return { iife, moduleSource };
}

export function writeFoucBoots(filter?: string): FoucBootTarget[] {
  const targets = resolveFoucBoots(filter);
  for (const target of targets) {
    const { iife } = writeFoucBoot(target);
    console.log(
      `Wrote ${path.relative(ROOT, target.out)} (${iife.length} bytes IIFE) [${target.id}]`,
    );
  }
  return targets;
}

const isMain =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isMain) {
  const filter = process.argv[2];
  writeFoucBoots(filter);
}
