import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { ROOT } from "../lib/paths";
import { resolveFoucBoots, type FoucBootTarget } from "./registry";

export function buildFoucBootIife(entry: string): string {
  const dir = mkdtempSync(path.join(tmpdir(), "fouc-boot-"));
  const outfile = path.join(dir, "boot.js");

  try {
    execFileSync(
      "bun",
      [
        "build",
        entry,
        "--outfile",
        outfile,
        "--format",
        "iife",
        "--target",
        "browser",
        "--minify",
      ],
      {
        cwd: ROOT,
        stdio: ["ignore", "pipe", "pipe"],
        encoding: "utf8",
      },
    );

    return readFileSync(outfile, "utf8").trim();
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

export function renderFoucBootModule(exportName: string, iife: string): string {
  return [
    "/** Generated by `bun run fouc:boot` — do not edit. */",
    `export const ${exportName} = ${JSON.stringify(iife)};`,
    "",
  ].join("\n");
}

export function hashFoucBootScript(source: string): string {
  return createHash("sha256").update(source).digest("hex");
}

export function writeFoucBoot(target: FoucBootTarget): {
  iife: string;
  moduleSource: string;
} {
  const iife = buildFoucBootIife(target.entry);
  const moduleSource = renderFoucBootModule(target.exportName, iife);
  writeFileSync(target.out, moduleSource, "utf8");
  return { iife, moduleSource };
}

export function writeFoucBoots(filter?: string): FoucBootTarget[] {
  const targets = resolveFoucBoots(filter);
  for (const target of targets) {
    const { iife } = writeFoucBoot(target);
    console.log(
      `Wrote ${path.relative(ROOT, target.out)} (${iife.length} bytes IIFE) [${target.id}]`,
    );
  }
  return targets;
}

const isMain =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url));

if (isMain) {
  const filter = process.argv[2];
  writeFoucBoots(filter);
}
