<main class="mx-auto w-[min(820px,calc(100%-48px))] py-9 pb-[74px] max-[620px]:w-[calc(100%-28px)] max-[620px]:py-7">
  <header>
    <nav class="flex gap-2 text-xs text-slate-500" aria-label="Breadcrumb"><a class="text-blue-800 underline underline-offset-2" href="/grammar">Grammar</a><span>/</span><span>Language terms</span></nav>
    <p class="mb-2 mt-6 text-xs font-semibold uppercase tracking-widest text-blue-700">Grammar reference</p><h1 class="text-5xl font-semibold tracking-tight text-slate-900">Language terms</h1><p class="mt-3 max-w-2xl font-serif text-base text-slate-700">Short definitions for the terms used in this reference.</p>
  </header>
  <dl class="mt-9 border-t border-slate-300">
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Case</dt><dd class="m-0 font-serif leading-6 text-slate-700">A word's job in a sentence, shown by its form. Slovak has six active cases.</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/cases-overview">Open cases →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Declension</dt><dd class="m-0 font-serif leading-6 text-slate-700">The set of ending changes used by nouns, adjectives, pronouns, and numerals for case, number, and gender.</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/cases-overview">See declension through cases →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Conjugation</dt><dd class="m-0 font-serif leading-6 text-slate-700">The set of verb-form changes for person, number, tense, mood, and sometimes gender.</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/present-tense">Open present tense →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Tense</dt><dd class="m-0 font-serif leading-6 text-slate-700">The time of an action: present, past, or future. Tense is one part of conjugation.</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/present-tense">Open present tense →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Gender</dt><dd class="m-0 font-serif leading-6 text-slate-700">A noun class: masculine, feminine, or neuter. Gender affects related word endings.</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/grammatical-gender">Open grammatical gender →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Agreement</dt><dd class="m-0 font-serif leading-6 text-slate-700">When related words take matching forms, such as an adjective matching a noun's gender, number, and case.</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/grammatical-gender">See agreement →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Infinitive</dt><dd class="m-0 font-serif leading-6 text-slate-700">The dictionary form of a verb: its unconjugated base form, such as rozumieť, “to understand.”</dd><a class="whitespace-nowrap text-xs font-bold text-blue-800 underline underline-offset-2" href="/grammar/present-tense">See verb forms →</a></div>
    <div class="grid grid-cols-[160px_minmax(0,1fr)_auto] items-start gap-5 border-b border-slate-200 px-3 py-4 max-[620px]:grid-cols-1 max-[620px]:gap-1"><dt class="font-serif text-lg font-bold text-blue-800">Aspect</dt><dd class="m-0 font-serif leading-6 text-slate-700">Whether a verb presents an action as completed or ongoing. This reference will cover it separately.</dd></div>
  </dl>
</main>
