import type { PracticeItem } from "$lib/learning/types";

export const grammarPracticeItems: PracticeItem[] = [
  {
    id: "grammar/first-person-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-first-person-reading",
      type: "choice",
      practiceItemId: "grammar/first-person-reading",
      prompt: "I am reading a book.",
      choices: [
        { id: "first-person", label: "Čítam knihu." },
        {
          id: "third-person",
          label: "Číta knihu.",
          whyWrong: "**Číta** ends in **-a** for he/she — not I.",
        },
        {
          id: "second-person",
          label: "Čítaš knihu.",
          whyWrong: "**Čítaš** ends in **-š** for informal you — not I.",
        },
      ],
      answerId: "first-person",
      feedback: {
        correction: "Čítam knihu.",
        english: "I am reading a book.",
        why: "The ending **-m** marks I. **Číta** is he/she; **čítaš** is informal you.",
      },
    },
    feedback: {
      correction: "Čítam knihu.",
      english: "I am reading a book.",
      why: "The ending **-m** marks I. **Číta** is he/she; **čítaš** is informal you.",
    },
    newUse: "Try a new first-person sentence: Dnes pracujem.",
  },
  {
    id: "grammar/repair-first-person-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-repair-first-person-reading",
      type: "typed",
      task: "repair",
      practiceItemId: "grammar/repair-first-person-reading",
      context: [
        {
          id: "review-reading-caption",
          speaker: "Sentence",
          slovak: "Ja číta noviny.",
          english: "I am reading a newspaper.",
        },
      ],
      prompt: "Repair this sentence.",
      inputLabel: "Correct Slovak sentence",
      answer: "Čítam noviny.",
      acceptedAnswers: ["Ja čítam noviny."],
      feedback: {
        correction: "Čítam noviny.",
        english: "I am reading a newspaper.",
        why: "**Číta** describes one other person. Change the ending to **-m** when you are the reader.",
      },
    },
    feedback: {
      correction: "Čítam noviny.",
      english: "I am reading a newspaper.",
      why: "**Číta** describes one other person. Change the ending to **-m** when you are the reader.",
    },
  },
  {
    id: "grammar/today-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-today-reading",
      type: "choice",
      practiceItemId: "grammar/today-reading",
      prompt: "Today we are reading a book.",
      choices: [
        { id: "we", label: "Dnes čítame knihu." },
        {
          id: "i",
          label: "Dnes čítam knihu.",
          whyWrong: "**Čítam** ends in **-m** for I — not we.",
        },
        {
          id: "they",
          label: "Dnes čítajú knihu.",
          whyWrong: "**Čítajú** ends in **-jú** for they — not we.",
        },
      ],
      answerId: "we",
      feedback: {
        correction: "Dnes čítame knihu.",
        english: "Today we are reading a book.",
        why: "**Čítame** ends in **-me** for we. **Čítam** is I; **čítajú** is they.",
      },
    },
    feedback: {
      correction: "Dnes čítame knihu.",
      english: "Today we are reading a book.",
      why: "**Čítame** ends in **-me** for we. **Čítam** is I; **čítajú** is they.",
    },
  },
  {
    id: "grammar/cloze-first-person-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-first-person-reading",
      type: "cloze",
      practiceItemId: "grammar/cloze-first-person-reading",
      prompt: "Fill the gap so the sentence is about you.",
      frame: "Dnes {} knihu.",
      answer: "čítam",
      gapEn: "I read / I am reading",
      lemmaId: "citat",
      morphHint: "čítať → čítam",
      sentenceEn: "Today I am reading a book.",
      hint: {
        chip: "1st person sg. · -m",
        grammarTopicId: "present-tense",
        note: "The -m ending marks I. Slovak often drops ja because the ending already says who acts.",
        reveal: ["The verb is čítať.", "First person singular takes -m.", "č í t a …"],
      },
      feedback: {
        correction: "Dnes čítam knihu.",
        english: "Today I am reading a book.",
        why: "**Čítam** ends in **-m** for I. The blank needs the first-person form, not **číta**.",
      },
    },
    feedback: {
      correction: "Dnes čítam knihu.",
      english: "Today I am reading a book.",
      why: "**Čítam** ends in **-m** for I. The blank needs the first-person form, not **číta**.",
    },
  },
  {
    id: "grammar/cloze-second-person-speaking",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-second-person-speaking",
      type: "cloze",
      practiceItemId: "grammar/cloze-second-person-speaking",
      prompt: "Ask someone informally if they speak Slovak — fill the gap.",
      frame: "{} po slovensky?",
      answer: "hovoríš",
      gapEn: "you speak",
      lemmaId: "hovorit",
      morphHint: "hovoriť → hovoríš",
      sentenceEn: "Do you speak Slovak?",
      hint: {
        chip: "2nd person sg. · -š",
        grammarTopicId: "present-tense",
        note: "The -š ending marks you (singular, informal). Contrast with -m for I.",
        reveal: [
          "The verb is hovoriť.",
          "Second person singular takes -š.",
          "h o v o r í …",
        ],
      },
      feedback: {
        correction: "Hovoríš po slovensky?",
        english: "Do you speak Slovak?",
        why: "**Hovoríš** ends in **-š** for informal you. **Hovorím** would mean I speak.",
      },
    },
    feedback: {
      correction: "Hovoríš po slovensky?",
      english: "Do you speak Slovak?",
      why: "**Hovoríš** ends in **-š** for informal you. **Hovorím** would mean I speak.",
    },
  },
  {
    id: "grammar/cloze-third-person-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-third-person-reading",
      type: "cloze",
      practiceItemId: "grammar/cloze-third-person-reading",
      prompt: "Fill the gap for Peter.",
      frame: "Peter {} knihu.",
      answer: "číta",
      gapEn: "he reads / he is reading",
      lemmaId: "citat",
      morphHint: "čítať → číta",
      sentenceEn: "Peter is reading a book.",
      hint: {
        chip: "3rd person sg. · stem",
        grammarTopicId: "present-tense",
        note: "Third person singular uses the present stem with no -m or -š. Peter, Anna, or on/ona take this form.",
        reveal: ["The verb is čítať.", "Third person singular has no -m/-š.", "č í t a"],
      },
      feedback: {
        correction: "Peter číta knihu.",
        english: "Peter is reading a book.",
        why: "**Číta** is he/she reads. **Čítam** would mean I am reading.",
      },
    },
    feedback: {
      correction: "Peter číta knihu.",
      english: "Peter is reading a book.",
      why: "**Číta** is he/she reads. **Čítam** would mean I am reading.",
    },
  },
  {
    id: "grammar/cloze-we-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-we-reading",
      type: "cloze",
      practiceItemId: "grammar/cloze-we-reading",
      prompt: "Fill the gap so the sentence is about us.",
      frame: "Dnes {} knihu.",
      answer: "čítame",
      gapEn: "we read / we are reading",
      lemmaId: "citat",
      morphHint: "čítať → čítame",
      sentenceEn: "Today we are reading a book.",
      hint: {
        chip: "1st person pl. · -me",
        grammarTopicId: "present-tense",
        note: "The -me ending marks we. Contrast with -m for I and -jú for they.",
        reveal: ["The verb is čítať.", "First person plural takes -me.", "č í t a …"],
      },
      feedback: {
        correction: "Dnes čítame knihu.",
        english: "Today we are reading a book.",
        why: "**Čítame** ends in **-me** for we. **Čítam** is I; **čítajú** is they.",
      },
    },
    feedback: {
      correction: "Dnes čítame knihu.",
      english: "Today we are reading a book.",
      why: "**Čítame** ends in **-me** for we. **Čítam** is I; **čítajú** is they.",
    },
  },
  {
    id: "grammar/cloze-formal-speaking",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-formal-speaking",
      type: "cloze",
      practiceItemId: "grammar/cloze-formal-speaking",
      prompt: "Ask politely if someone speaks Slovak — fill the gap.",
      frame: "{} po slovensky?",
      answer: "hovoríte",
      gapEn: "you speak (formal / plural)",
      lemmaId: "hovorit",
      morphHint: "hovoriť → hovoríte",
      sentenceEn: "Do you speak Slovak?",
      hint: {
        chip: "2nd person pl. · -te",
        grammarTopicId: "present-tense",
        note: "The -te ending marks vy — plural you, or formal singular you. Hovoríš is informal singular.",
        reveal: [
          "The verb is hovoriť.",
          "Second person plural / formal takes -te.",
          "h o v o r í …",
        ],
      },
      feedback: {
        correction: "Hovoríte po slovensky?",
        english: "Do you speak Slovak?",
        why: "**Hovoríte** ends in **-te** for polite or plural you. **Hovoríš** is informal singular.",
      },
    },
    feedback: {
      correction: "Hovoríte po slovensky?",
      english: "Do you speak Slovak?",
      why: "**Hovoríte** ends in **-te** for polite or plural you. **Hovoríš** is informal singular.",
    },
  },
  {
    id: "grammar/cloze-they-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-they-reading",
      type: "cloze",
      practiceItemId: "grammar/cloze-they-reading",
      prompt: "Fill the gap for more than one person.",
      frame: "Oni {} knihu.",
      answer: "čítajú",
      gapEn: "they read / they are reading",
      lemmaId: "citat",
      morphHint: "čítať → čítajú",
      sentenceEn: "They are reading a book.",
      hint: {
        chip: "3rd person pl. · -jú",
        grammarTopicId: "present-tense",
        note: "The -jú ending marks they. Contrast with číta for one other person.",
        reveal: ["The verb is čítať.", "Third person plural takes -jú.", "č í t a …"],
      },
      feedback: {
        correction: "Oni čítajú knihu.",
        english: "They are reading a book.",
        why: "**Čítajú** ends in **-jú** for they. **Číta** is one other person reading.",
      },
    },
    feedback: {
      correction: "Oni čítajú knihu.",
      english: "They are reading a book.",
      why: "**Čítajú** ends in **-jú** for they. **Číta** is one other person reading.",
    },
  },
  {
    id: "grammar/cloze-first-person-working",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-first-person-working",
      type: "cloze",
      practiceItemId: "grammar/cloze-first-person-working",
      prompt: "Fill the gap so the sentence is about you.",
      frame: "Zajtra {} v Bratislave.",
      answer: "pracujem",
      gapEn: "I work / I am working",
      lemmaId: "pracovat",
      morphHint: "pracovať → pracujem",
      sentenceEn: "Tomorrow I am working in Bratislava.",
      hint: {
        chip: "1st person sg. · -m",
        grammarTopicId: "present-tense",
        note: "Present -m still marks I. Pracovať takes the stem pracuj- before the ending.",
        reveal: [
          "The verb is pracovať.",
          "First person singular takes -m.",
          "p r a c u j …",
        ],
      },
      feedback: {
        correction: "Zajtra pracujem v Bratislave.",
        english: "Tomorrow I am working in Bratislava.",
        why: "**Pracujem** is I work. Keep **-m** when you are the one working.",
      },
    },
    feedback: {
      correction: "Zajtra pracujem v Bratislave.",
      english: "Tomorrow I am working in Bratislava.",
      why: "**Pracujem** is I work. Keep **-m** when you are the one working.",
    },
  },
  {
    id: "grammar/cloze-second-person-working",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-cloze-second-person-working",
      type: "cloze",
      practiceItemId: "grammar/cloze-second-person-working",
      prompt: "Fill the gap for informal you.",
      frame: "Dnes {} v Bratislave.",
      answer: "pracuješ",
      gapEn: "you work / you are working",
      lemmaId: "pracovat",
      morphHint: "pracovať → pracuješ",
      sentenceEn: "Today you are working in Bratislava.",
      hint: {
        chip: "2nd person sg. · -š",
        grammarTopicId: "present-tense",
        note: "The -š ending marks informal singular you. Contrast with -m for I.",
        reveal: [
          "The verb is pracovať.",
          "Second person singular takes -š.",
          "p r a c u j e …",
        ],
      },
      feedback: {
        correction: "Dnes pracuješ v Bratislave.",
        english: "Today you are working in Bratislava.",
        why: "**Pracuješ** ends in **-š** for informal you. **Pracujem** would mean I work.",
      },
    },
    feedback: {
      correction: "Dnes pracuješ v Bratislave.",
      english: "Today you are working in Bratislava.",
      why: "**Pracuješ** ends in **-š** for informal you. **Pracujem** would mean I work.",
    },
  },
  {
    id: "grammar/choice-they-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-choice-they-reading",
      type: "choice",
      practiceItemId: "grammar/choice-they-reading",
      prompt: "They are reading a book.",
      choices: [
        { id: "they", label: "Čítajú knihu." },
        {
          id: "we",
          label: "Čítame knihu.",
          whyWrong: "**Čítame** ends in **-me** for we — not they.",
        },
        {
          id: "he",
          label: "Číta knihu.",
          whyWrong: "**Číta** ends in **-a** for he/she — not they.",
        },
      ],
      answerId: "they",
      feedback: {
        correction: "Čítajú knihu.",
        english: "They are reading a book.",
        why: "**Čítajú** ends in **-jú** for they. **Čítame** is we; **číta** is he/she.",
      },
    },
    feedback: {
      correction: "Čítajú knihu.",
      english: "They are reading a book.",
      why: "**Čítajú** ends in **-jú** for they. **Čítame** is we; **číta** is he/she.",
    },
  },
  {
    id: "grammar/choice-formal-speaking",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-choice-formal-speaking",
      type: "choice",
      practiceItemId: "grammar/choice-formal-speaking",
      prompt: "Do you speak Slovak?",
      choices: [
        { id: "formal", label: "Hovoríte po slovensky?" },
        {
          id: "informal",
          label: "Hovoríš po slovensky?",
          whyWrong:
            "**Hovoríš** is informal singular — this question needs polite **hovoríte**.",
        },
        {
          id: "i",
          label: "Hovorím po slovensky?",
          whyWrong: "**Hovorím** is I speak — the prompt asks for a question to **you**.",
        },
      ],
      answerId: "formal",
      feedback: {
        correction: "Hovoríte po slovensky?",
        english: "Do you speak Slovak?",
        why: "**Hovoríte** (**-te**) is polite or plural. **Hovoríš** is informal singular.",
      },
    },
    feedback: {
      correction: "Hovoríte po slovensky?",
      english: "Do you speak Slovak?",
      why: "**Hovoríte** (**-te**) is polite or plural. **Hovoríš** is informal singular.",
    },
  },
  {
    id: "grammar/repair-second-person-speaking",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-repair-second-person-speaking",
      type: "typed",
      task: "repair",
      practiceItemId: "grammar/repair-second-person-speaking",
      context: [
        {
          id: "review-second-person-speaking-broken",
          speaker: "Sentence",
          slovak: "Ty hovorím po slovensky.",
          english: "You speak Slovak.",
        },
      ],
      prompt: "Repair this sentence.",
      inputLabel: "Correct Slovak sentence",
      answer: "Hovoríš po slovensky.",
      acceptedAnswers: ["Ty hovoríš po slovensky."],
      feedback: {
        correction: "Hovoríš po slovensky.",
        english: "You speak Slovak.",
        why: "**Hovorím** means I speak. Use **hovoríš** when speaking to one person informally.",
      },
    },
    feedback: {
      correction: "Hovoríš po slovensky.",
      english: "You speak Slovak.",
      why: "**Hovorím** means I speak. Use **hovoríš** when speaking to one person informally.",
    },
  },
  {
    id: "grammar/build-we-reading",
    source: {
      kind: "lesson",
      label: "Present-tense endings",
      href: "/lessons/grammar/present-tense-i",
    },
    task: {
      id: "review-build-we-reading",
      type: "build",
      practiceItemId: "grammar/build-we-reading",
      prompt: "Today we are reading a book.",
      tiles: ["knihu.", "Dnes", "čítame", "čítam"],
      answer: ["Dnes", "čítame", "knihu."],
      feedback: {
        correction: "Dnes čítame knihu.",
        english: "Today we are reading a book.",
        why: "**Čítame** ends in **-me** for we. **Čítam** would mean I am reading.",
      },
    },
    feedback: {
      correction: "Dnes čítame knihu.",
      english: "Today we are reading a book.",
      why: "**Čítame** ends in **-me** for we. **Čítam** would mean I am reading.",
    },
  },
  {
    id: "grammar/byt-som",
    source: {
      kind: "lesson",
      label: "Present forms of byť",
      href: "/lessons/grammar/byt-present",
    },
    task: {
      id: "review-byt-som",
      type: "typed",
      task: "complete",
      practiceItemId: "grammar/byt-som",
      context: [
        {
          id: "review-byt-som-introduction",
          speaker: "Anna",
          slovak: "Ahoj! Ako sa voláš?",
          english: "Hi! What is your name?",
        },
      ],
      prompt: "I am Alex.",
      inputLabel: "Your Slovak answer",
      answer: "Som Alex.",
      feedback: {
        correction: "Som Alex.",
        english: "I am Alex.",
        why: "**Som** is the first-person singular present form of **byť**, “to be.”",
      },
    },
    feedback: {
      correction: "Som Alex.",
      english: "I am Alex.",
      why: "**Som** is the first-person singular present form of **byť**, “to be.”",
    },
    newUse: "Now say: Som študent / Som študentka.",
  },
  {
    id: "grammar/byt-ste",
    source: {
      kind: "lesson",
      label: "Present forms of byť",
      href: "/lessons/grammar/byt-present",
    },
    task: {
      id: "review-byt-ste",
      type: "typed",
      task: "complete",
      practiceItemId: "grammar/byt-ste",
      context: [
        {
          id: "review-byt-ste-call",
          speaker: "Marek",
          slovak: "Som pri vchode.",
          english: "I am by the entrance.",
        },
      ],
      prompt: "Where are you?",
      inputLabel: "Your Slovak question",
      answer: "Kde ste?",
      feedback: {
        correction: "Kde ste?",
        english: "Where are you?",
        why: "**Ste** is the present form of **byť** for formal singular you or plural you.",
      },
    },
    feedback: {
      correction: "Kde ste?",
      english: "Where are you?",
      why: "**Ste** is the present form of **byť** for formal singular you or plural you.",
    },
  },
  {
    id: "grammar/byt-je-location",
    source: {
      kind: "lesson",
      label: "Present forms of byť",
      href: "/lessons/grammar/byt-present",
    },
    task: {
      id: "review-byt-je-location",
      type: "typed",
      task: "complete",
      practiceItemId: "grammar/byt-je-location",
      context: [
        {
          id: "review-byt-je-location-question",
          speaker: "Anna",
          slovak: "Kde je Peter?",
          english: "Where is Peter?",
        },
      ],
      prompt: "He is in Bratislava.",
      inputLabel: "Your Slovak answer",
      answer: "Je v Bratislave.",
      feedback: {
        correction: "Je v Bratislave.",
        english: "He/She is in Bratislava.",
        why: "**Je** is he/she/it is. After **v** for location, Bratislava changes to **v Bratislave**.",
      },
    },
    feedback: {
      correction: "Je v Bratislave.",
      english: "He/She is in Bratislava.",
      why: "**Je** is he/she/it is. After **v** for location, Bratislava changes to **v Bratislave**.",
    },
    newUse: "Ask: Kde je Peter?",
  },
  {
    id: "grammar/mat-mam",
    source: {
      kind: "lesson",
      label: "Present forms of mať",
      href: "/lessons/grammar/mat-present",
    },
    task: {
      id: "review-mat-mam",
      type: "typed",
      task: "complete",
      practiceItemId: "grammar/mat-mam",
      context: [
        {
          id: "review-mat-mam-question",
          speaker: "Anna",
          slovak: "Máš teraz chvíľu?",
          english: "Do you have a moment now?",
        },
      ],
      prompt: "I have time.",
      inputLabel: "Your Slovak answer",
      answer: "Mám čas.",
      feedback: {
        correction: "Mám čas.",
        english: "I have time.",
        why: "**Mám** is the first-person singular present form of **mať**, “to have.”",
      },
    },
    feedback: {
      correction: "Mám čas.",
      english: "I have time.",
      why: "**Mám** is the first-person singular present form of **mať**, “to have.”",
    },
  },
  {
    id: "grammar/mat-mas",
    source: {
      kind: "lesson",
      label: "Present forms of mať",
      href: "/lessons/grammar/mat-present",
    },
    task: {
      id: "review-mat-mas",
      type: "typed",
      task: "complete",
      practiceItemId: "grammar/mat-mas",
      context: [
        {
          id: "review-mat-mas-train",
          speaker: "Waiter",
          slovak: "Prosím, lístok.",
          english: "Ticket, please.",
        },
      ],
      prompt: "Do you have a ticket?",
      inputLabel: "Your Slovak question",
      answer: "Máš lístok?",
      feedback: {
        correction: "Máš lístok?",
        english: "Do you have a ticket?",
        why: "**Máš** is the present form of **mať** for one person you address informally.",
      },
    },
    feedback: {
      correction: "Máš lístok?",
      english: "Do you have a ticket?",
      why: "**Máš** is the present form of **mať** for one person you address informally.",
    },
  },
  {
    id: "grammar/mat-nemam",
    source: {
      kind: "lesson",
      label: "Present forms of mať",
      href: "/lessons/grammar/mat-present",
    },
    task: {
      id: "review-mat-nemam",
      type: "typed",
      task: "complete",
      practiceItemId: "grammar/mat-nemam",
      context: [
        {
          id: "review-mat-nemam-invitation",
          speaker: "Anna",
          slovak: "Poďme na kávu.",
          english: "Let’s go for coffee.",
        },
      ],
      prompt: "I don’t have time.",
      inputLabel: "Your Slovak answer",
      answer: "Nemám čas.",
      feedback: {
        correction: "Nemám čas.",
        english: "I don’t have time.",
        why: "Negation attaches to the verb: **mám** becomes **nemám**, not **nie mám**.",
      },
    },
    feedback: {
      correction: "Nemám čas.",
      english: "I don’t have time.",
      why: "Negation attaches to the verb: **mám** becomes **nemám**, not **nie mám**.",
    },
    newUse: "Add: Prepáč, nemám čas.",
  },
];
