import { languageSource } from "../sources";
import type { PronunciationTopic } from "../types";

export const pronunciationEntries: PronunciationTopic[] = [
  {
    slug: "slovak-alphabet",
    slovak: "slovenská abeceda",
    english: "Slovak alphabet",
    category: "Spelling",
    kind: "pronunciation",
    summary: "Learn the letters, diacritics, and ch as one Slovak digraph.",
    body: [
      "The Slovak alphabet has 46 letters, including letters with diacritics and the digraphs dz, dž, and ch. Acute marks show long vowels, while the caron marks several changed consonants and vowels.",
      "Treat ch as one letter in the alphabet and as one sound in a word. It comes after h in alphabetical order, so chlieb begins with the single digraph ch, not a separate c followed by h.",
    ],
    examples: [
      { slovak: "čo", english: "what" },
      { slovak: "žena", english: "woman" },
      { slovak: "chlieb", english: "bread" },
    ],
    related: ["soft-consonants", "vowel-length", "co", "zena", "dakujem"],
    source: languageSource,
    tags: ["alphabet", "spelling", "beginner"],
    pathGroup: "Spelling",
    order: 1,
    goal: "Recognize Slovak letters and the digraph ch.",
    contrasts: [
      { left: "c", right: "č", note: "plain c / caron" },
      { left: "s", right: "š", note: "plain s / caron" },
      { left: "ch", right: "c + h", note: "one digraph / two letters" },
    ],
    mouthCue:
      "Read each marked letter clearly, then make ch as one breathy sound instead of pausing between c and h.",
    practiceWords: ["čo", "žena", "chlieb"],
    practicePhrase: {
      slovak: "Čo je chlieb?",
      english: "What is bread?",
    },
    nextSlug: "first-syllable-stress",
  },
  {
    slug: "first-syllable-stress",
    slovak: "prízvuk na prvej slabike",
    english: "first-syllable stress",
    category: "Rhythm",
    kind: "pronunciation",
    summary: "Slovak normally stresses the first syllable of a word.",
    body: [
      "Keep the stress steady and light. Long vowel marks show vowel length, not stress.",
      "Prepositions can form one rhythmic unit with the following word, so the stress may fall on the preposition.",
    ],
    examples: [
      { slovak: "BRAtislava", english: "Bratislava" },
      { slovak: "ĎAkujem", english: "thank you" },
    ],
    related: ["dakujem", "vowel-length", "rhythmic-law"],
    source: languageSource,
    tags: ["stress", "rhythm", "beginner"],
    pathGroup: "Rhythm",
    order: 2,
    goal: "Hear and place the steady first-syllable beat.",
    contrasts: [
      { left: "BRAtislava", right: "bra-ti-SLA-va", note: "Stress first syllable" },
      { left: "ĎAkujem", right: "ďa-KU-jem", note: "Keep later syllables light" },
    ],
    mouthCue:
      "Give the first syllable a small lift. Keep the rest even; do not stretch it for stress.",
    practiceWords: ["Bratislava", "ďakujem", "prosím"],
    practicePhrase: { slovak: "Ďakujem za pomoc.", english: "Thank you for the help." },
    nextSlug: "rhythmic-law",
  },
  {
    slug: "rhythmic-law",
    slovak: "rytmický zákon",
    english: "rhythmic law",
    category: "Rhythm",
    kind: "pronunciation",
    summary: "Native Slovak generally avoids two successive long syllables.",
    body: [
      "In native Slovak words, two long syllables usually do not follow one another. A long vowel or diphthong counts as a long syllable nucleus, so the next syllable is often shortened.",
      "This is why speakers say krásny rather than *krásný, bývam rather than *bývám, and múdry rather than *múdrý.",
      "Loans, some morphological environments, and compounds can be exceptions. Treat the rhythmic law as a strong native-word tendency, not a rule for generating every form.",
    ],
    examples: [
      { slovak: "krásny", english: "beautiful" },
      { slovak: "bývam", english: "I live" },
      { slovak: "múdry", english: "clever; wise" },
    ],
    related: ["vowel-length", "first-syllable-stress"],
    source: languageSource,
    tags: ["rhythm", "vowels", "intermediate"],
    pathGroup: "Rhythm",
    order: 3,
    goal: "Hear and produce the shortening that prevents two successive long syllables.",
    contrasts: [
      {
        left: "krásny",
        right: "krásný",
        note: "standard Slovak / two long syllables avoided",
      },
      { left: "bývam", right: "bývám", note: "standard Slovak / second vowel shortened" },
      { left: "múdry", right: "múdrý", note: "standard Slovak / second vowel shortened" },
    ],
    mouthCue:
      "Hold the first long vowel or diphthong, then keep the following syllable short and light instead of stretching both.",
    practiceWords: ["krásny", "bývam", "múdry", "mlieko"],
    practicePhrase: {
      slovak: "Bývam v krásnom dome.",
      english: "I live in a beautiful house.",
    },
    nextSlug: "vowel-length",
  },
  {
    slug: "vowel-length",
    slovak: "dĺžka samohlások",
    english: "vowel length",
    category: "Vowels",
    kind: "pronunciation",
    summary: "Acute marks make vowels longer and can distinguish words.",
    body: [
      "Hold á, é, í, ó, ú, and ý for roughly twice as long as their short partners.",
      "Length is meaningful. Preserve it even when the syllable does not carry stress.",
    ],
    examples: [
      { slovak: "káva", english: "coffee" },
      { slovak: "lístok", english: "ticket" },
    ],
    related: ["kava", "listok", "first-syllable-stress", "rhythmic-law"],
    source: languageSource,
    tags: ["vowels", "length", "beginner"],
    pathGroup: "Vowels",
    order: 4,
    goal: "Hold marked vowels longer without moving the stress.",
    contrasts: [
      { left: "a", right: "á", note: "short / long" },
      { left: "i", right: "í", note: "short / long" },
    ],
    mouthCue:
      "Keep the vowel shape steady. Length means more time, not more force or a different vowel.",
    practiceWords: ["káva", "lístok", "áno"],
    practicePhrase: { slovak: "Prosím si kávu.", english: "I would like coffee." },
    nextSlug: "soft-consonants",
  },
  {
    slug: "soft-consonants",
    slovak: "mäkké spoluhlásky",
    english: "soft consonants",
    category: "Consonants",
    kind: "pronunciation",
    summary: "The letters č, š, ž, ď, ť, ň, and ľ represent distinct consonants.",
    body: [
      "The caron changes the consonant sound. Treat each marked letter as its own sound rather than decoration.",
      "Practice minimal contrasts slowly, then place each sound in a short phrase.",
    ],
    examples: [
      { slovak: "čo", english: "what" },
      { slovak: "žena", english: "woman" },
    ],
    related: ["co", "zena", "dakujem"],
    source: languageSource,
    tags: ["consonants", "diacritics", "beginner"],
    pathGroup: "Consonants",
    order: 5,
    goal: "Treat marked consonants as distinct sounds, not decorated letters.",
    contrasts: [
      { left: "c", right: "č", note: "plain / caron" },
      { left: "s", right: "š", note: "plain / caron" },
    ],
    mouthCue:
      "For č, š, and ž, raise the tongue slightly and let the sound pass further back in the mouth.",
    practiceWords: ["čo", "žena", "ďakujem"],
    practicePhrase: { slovak: "Čo to znamená?", english: "What does that mean?" },
  },
];
