<script lang="ts">
  import { entryBySlug } from "$lib/content/data";
  import type { ContentEntry, PronunciationTopic } from "$lib/content/types";

  let { topic }: { topic: PronunciationTopic } = $props();
  const relatedEntries = $derived(topic.related.map((slug) => entryBySlug.get(slug)).filter((entry): entry is ContentEntry => entry !== undefined));
  const relatedWords = $derived(relatedEntries.filter((entry) => entry.kind === "word"));
  const relatedTopics = $derived(relatedEntries.filter((entry) => entry.kind !== "word"));
  const routeBase: Record<ContentEntry["kind"], string> = { grammar: "grammar", pronunciation: "pronunciation", word: "dictionary" };
</script>

<main class="mx-auto grid max-w-6xl grid-cols-[minmax(0,760px)_210px] justify-center gap-14 px-[30px] py-10 pb-[74px] max-[900px]:block max-[900px]:px-6 max-[900px]:py-8 max-[560px]:px-3.5 max-[560px]:py-7">
  <article class="min-w-0">
    <nav class="mb-5 flex gap-2 text-xs text-slate-500" aria-label="Breadcrumb"><a class="text-blue-800 underline underline-offset-2" href="/pronunciation">Pronunciation</a><span>/</span><span>{topic.pathGroup}</span></nav>
    <header class="border-b border-slate-200 pb-7"><p class="section-label">Pronunciation reference</p><h1>{topic.english}</h1><p class="mt-2 font-serif text-lg text-blue-800" lang="sk">{topic.slovak}</p><p class="mt-4 max-w-[66ch] font-serif text-lg text-slate-700">{topic.summary}</p></header>

    <section class="scroll-mt-[72px] pt-8"><p class="section-label">Overview</p><h2 id="goal-heading" class="mb-3 text-2xl">{topic.goal}</h2>{#each topic.body as paragraph (paragraph)}<p class="max-w-[66ch] font-serif leading-7 text-slate-700">{paragraph}</p>{/each}</section>
    <section class="scroll-mt-[72px] border-t border-slate-200 pt-8"><p class="section-label">Listen for</p><h2 id="contrast-heading" class="mb-3 text-2xl">Sound contrasts</h2><div class="mt-5 grid grid-cols-2 gap-2.5 max-[560px]:grid-cols-1">{#each topic.contrasts as contrast (contrast.left)}<div class="grid gap-1 rounded border border-slate-200 bg-slate-50 p-3.5"><strong class="font-serif text-blue-800" lang="sk">{contrast.left} / {contrast.right}</strong><span class="text-xs text-slate-500">{contrast.note}</span></div>{/each}</div></section>
    <section class="scroll-mt-[72px] border-t border-slate-200 pt-8"><div class="rounded border border-slate-300 bg-blue-50 p-5"><p class="section-label">Articulation</p><h2 id="cue-heading" class="mb-3 text-2xl">How it is formed</h2><p class="mb-0 max-w-[66ch] font-serif leading-7 text-slate-700">{topic.mouthCue}</p></div></section>
    <section class="scroll-mt-[72px] border-t border-slate-200 pt-8"><p class="section-label">Examples</p><h2 id="practice-heading" class="mb-3 text-2xl">Words and phrase</h2><div class="mt-4 flex flex-wrap gap-2">{#each topic.practiceWords as word (word)}<span class="rounded-full border border-slate-300 px-2.5 py-1.5 font-serif text-blue-800" lang="sk">{word}</span>{/each}</div><blockquote class="mt-4 grid gap-1 border-l-4 border-blue-600 bg-slate-50 px-4 py-3"><strong class="font-serif" lang="sk">{topic.practicePhrase.slovak}</strong><span class="text-sm text-slate-500">{topic.practicePhrase.english}</span></blockquote></section>
  </article>
  <aside class="sticky top-(--header-height) h-fit border-l border-slate-200 pl-5 max-[900px]:static max-[900px]:mt-9 max-[900px]:grid max-[900px]:grid-cols-2 max-[900px]:gap-8 max-[900px]:border-l-0 max-[900px]:border-t max-[900px]:pl-0 max-[900px]:pt-6 max-[560px]:grid-cols-1"><section><p class="rail-label">In this sound</p><nav class="grid"> <a class="py-1.5 font-serif text-sm text-slate-700 hover:text-blue-800 hover:underline" href="#goal-heading">Hear and say</a><a class="py-1.5 font-serif text-sm text-slate-700 hover:text-blue-800 hover:underline" href="#contrast-heading">Contrasts</a><a class="py-1.5 font-serif text-sm text-slate-700 hover:text-blue-800 hover:underline" href="#cue-heading">Mouth cue</a><a class="py-1.5 font-serif text-sm text-slate-700 hover:text-blue-800 hover:underline" href="#practice-heading">Practice</a></nav></section>{#if relatedWords.length}<section><p class="rail-label">Practice words</p>{#each relatedWords as word (word.slug)}<a class="grid gap-0.5 py-1.5 font-serif text-sm text-slate-700 hover:text-blue-800 hover:underline" href="/dictionary/{word.slug}" lang="sk">{word.slovak}<small class="text-xs text-slate-500">{word.english}</small></a>{/each}</section>{/if}{#if relatedTopics.length}<section><p class="rail-label">Related topics</p>{#each relatedTopics as entry (entry.slug)}<a class="grid gap-0.5 py-1.5 font-serif text-sm text-slate-700 hover:text-blue-800 hover:underline" href="/{routeBase[entry.kind]}/{entry.slug}">{entry.english}<small class="text-xs text-slate-500">{entry.slovak}</small></a>{/each}</section>{/if}</aside>
</main>
